version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: guns
      POSTGRES_PASSWORD: guns
      POSTGRES_DB: guns
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U guns']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-05-01T00-00-00Z
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: ../infra/backend.Dockerfile
    env_file: ./backend/.env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://guns:guns@postgres:5432/guns
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: guns-assets
      ASSET_BASE_URL: http://localhost:4000/uploads
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/frontend.Dockerfile
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
